### ISSUE TITLE
Upsert behavior

### ISSUE THREAD

**Issue by git4sun** [outr/scarango#10]
When I was trying upsert, its behavior is a bit strange. I was expecting that if there exists a post with name "abc", it will do the update, and if not insert as a new doc. But here's what I got:

    case class Post(name:String, _key: Option[String] = None,
                  _id: Option[String] = None,
                  _rev: Option[String] = None) extends DocumentOption

    DB.posts.upsert((Post("abc")))

    java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.outr.arango.ArangoDocument.upsert(ArangoDocument.scala:40)
	at com.outr.arango.managed.AbstractCollection$managed$.upsert(AbstractCollection.scala:80)

I saw the source code as: 

    val queryString =
          s"""
             |UPSERT { _key: @key }
             |INSERT $jsonString
             |UPDATE $jsonString IN ${collection.collection}
             |RETURN NEW
           """.stripMargin
        val query = Query(queryString, Map("key" -> Value.string(document._key.get)))

Should it be like:

             |UPSERT {name: @name }
             |INSERT {name: @name }
             |UPDATE {name: @name } IN ${collection.collection}

**Comment by darkfrog26** [comment]
You can only upsert if you provide an `_key`.  Otherwise, you're inserting.

**Comment by git4sun** [comment]
but you don't need to provide _key in AQL to upsert

**Comment by darkfrog26** [comment]
No, but you need to supply the unique identifier and in Scarango (for now at least) that's hard-coded as the `_key`.  You could update your code to use `_key` as a replacement for `name` and everything should work fine.

**Comment by darkfrog26** [comment]
This should be a non-issue in 2.0 since it focuses much more on client-side id generation and uses optimized upsert support.  While the API support doesn't include non-id-based upserts, you can still accomplish this via AQL if necessary.
