### ISSUE TITLE
aql query and Credentials conflict?

### ISSUE THREAD

**Issue by git4sun** [outr/scarango#11]
I created a graph with vertices and edges and with my Credentials. The import looks like this:

    import com.outr.arango.{Credentials, DocumentOption, Edge}

Then I was trying to execute a AQL query 

    val q = aql"let n = length(for v,e,p in 1 INBOUND 'Users/1' GRAPH 'tmp' return e) return n"

This requires `import com.outr.arango._`. I don't know which class exactly to import for using `aql`. So I did import everything.  Then suddenly the program complains about Credentials

    Error:(19, 17) exception during macro expansion: Error: error: true, message: Wrong credentials, 
    code: code: 401, title: ERROR_HTTP_UNAUTHORIZED, message: Will be raised when authorization is 
    required but the user is not authorized.,
    URL: http://localhost:8529/_open/auth (Method: POST, Status: HttpResponseStatus(401: 
    Unauthorized)),
    Request: {
      "username" : "root",
     "password" : "root"
    },
    Response: {"error":true,"errorMessage":"Wrong credentials","code":401,"errorNum":401}
            val q = aql"let n = length(for v,e,p in 1 INBOUND 'Users/1' GRAPH 'tmp' return e) return n"

Why importing everything overrides the Credentials. I didn't use root/root to create the Graph. 

BTW, the AQL query in my case is not to return a document. But the `cursor` in `VertexCollection` or `EdgeCollection` will return the Document object. And the `cursor` in `Graph` returns Nothing. How do I get the value from my query?

**Comment by darkfrog26** [comment]
1.) You do need to import wildcard for the `aql` interpolator
2.) It's coincidence that you're seeing a credentials issue after the import...there should be no connection
3.) You appear to either be loading a configuration file or are explicitly setting the username/password somewhere

**Comment by darkfrog26** [comment]
2.0 just released. Closing this issue as it should be irrelevant now.
