### ISSUE TITLE
ArangoDB cursor error

### ISSUE THREAD

**Issue by marcomedeiros96** [outr/scarango#112]
I'm currently working on an API in ZIO-HTTP and I'm using the scarango lib version 2.4.3. After some time the API stops being able to communicate with the Arango database and the following exception appears:

![image](https://user-images.githubusercontent.com/102588259/181264669-2f8eccf4-b7c8-40ee-8428-a4b3a6f66c2a.png)

Any idea what it could be?
Additional note: The database connection is static

**Comment by darkfrog26** [comment]
Yes, this is a known issue on the 2.x branch. Unfortunately, in ArangoDB the credentials eventually timeout and this occurs. You can change the server to make credentials stay active longer or have your service restart every few days to avoid it, but I'd recommend upgrading to 3.x for a better long-term solution.

**Comment by marcomedeiros96** [comment]
Thank you so much for explaining the error. Now I can solve the problem!
