### ISSUE TITLE
Support ArangoDB Driver 7.0

### ISSUE THREAD

**Issue by rashtao** [outr/scarango#152]
A first snapshot release of ArangoDB Java Driver version 7.0 has been published, see https://github.com/arangodb/arangodb-java-driver/releases/tag/v7.0.0-SNAPSHOT-1.

Please keep in mind that this is a snapshot release. It is suited for testing purposes only and is NOT for production usage. It is solely meant to allow users and libraries maintainers trying out the new features and reviewing the API changes, before the general availability of the stable release.

You might consider verifying if your project is compatible with it and can benefit from the new added features.

Here you can find a detailed description of the new features and API changes:
https://github.com/arangodb/arangodb-java-driver/blob/v7/docs

Feedback and questions are welcome in our dedicated `driverdev` Slack channel (https://arangodb-community.slack.com/archives/C1R1A2TFC).

--
Michele Rastelli
Java Engineer
ArangoDB GmbH

**Comment by rashtao** [comment]
The Async API will be reworked and re-added in a future version 7.x. Version 6 will be in the meanwhile still supported.

**Comment by rashtao** [comment]
Version [7.0.0](https://github.com/arangodb/arangodb-java-driver/releases/tag/v7.0.0) has been just released.

**Comment by darkfrog26** [comment]
Thanks for letting me know, but until 7.x has async support, Scarango won't be updating.

**Comment by darkfrog26** [comment]
In order to solve some threading issues resulting from ArangoDB Java Driver's async support I've gone ahead and upgraded to 7.
