### ISSUE TITLE
No support for ReplicationFactor in Graph and Collection

### ISSUE THREAD

**Issue by crajah** [outr/scarango#19]
In order to use ArangoDB Cloud (Oasis), a Replication Factor of at least 3 needs to be specified in the Graph and Collection objects.

I have made the following change to make it work.

https://gist.github.com/crajah/7861653fa20e0776ad7a2327bfd11192

**Comment by darkfrog26** [comment]
Would you be interested in submitting a PR for this?

**Comment by crajah** [comment]
Absolutely. I don't have access to submit a PR though.



*Chandan Rajah*
Chief Executive Officer
crajah@parallelai.com
+44 7711 060 452



This e-mail is confidential and may contain privileged information or
otherwise be protected. If you are not the intended recipient (or have
received this e-mail in error) please notify Parallel AI immediately by
e-mail at info@parallelai.com and permanently delete this e-mail from your
system. Any unauthorised copying, disclosure or distribution of the
material in this e-mail is strictly prohibited. Email communications cannot
be guaranteed to be secure or error free as information can, inter alia, be
corrupted, intercepted, lost, contain viruses or otherwise be altered.
Parallel AI may monitor outgoing and incoming messages for reasons of
security, to protect its respective businesses and to ensure compliance
with legal and regulatory obligations and its internal policies. In
communicating with us by email you understand and accept these risks, and
Parallel AI accepts no liability or responsibility for such matters or
their respective consequences.

**Comment by crajah** [comment]
Absolutely. I don't have access to submit a PR though. :-(

**Comment by darkfrog26** [comment]
What do you mean?  All you have to do in GitHub to submit a PR is to fork the project, commit your changes to your fork, and then submit that fork as a PR. No access is required except for having a GitHub account.

**Comment by crajah** [comment]
My mistake. I was attempting to create a branch. :-). I'll send a PR shortly.

**Comment by darkfrog26** [comment]
No worries, let me know if you have any trouble.
