### ISSUE TITLE
Dotty support

### ISSUE THREAD

**Issue by dwlizlo** [outr/scarango#22]
I believe it would be nice to target Dotty/Scala3 as there are more and more libraries being migrated. Not sure if there is a lot of work needed, for sure everything that is involving macros is a blocker.

**Comment by darkfrog26** [comment]
The two major hurdles here are:
1.) Circe doesn't support the latest releases of Dotty
2.) Yes, the Macros will be a pain, but once I have the library support I'll bite the bullet and do the switch.

I've added support for Dotty to most of my projects, but Circe and SourceCode have been blockers for me.

**Comment by dwlizlo** [comment]
There is milestone release of circe. Perhaps we could release milestone version until Scala3 is stable? WDYT?

**Comment by darkfrog26** [comment]
Can you point me to it? I only see it for `0.27`

**Comment by dwlizlo** [comment]
https://github.com/circe/circe/releases/tag/v0.14.0-M2 I believe it's this one

**Comment by darkfrog26** [comment]
Nice! Released today! I'll take a look and hopefully make some progress with Dotty support in Scarango this week.

**Comment by dwlizlo** [comment]
Please keep me updated, let me know if you could use some help :)

**Comment by darkfrog26** [comment]
Will do. Thanks.

**Comment by darkfrog26** [comment]
@dwlizlo I've made some good progress, but I'm currently stuck on adding support to Profig (my configuration library) to work on Scala 3 and upgrading the Macros. If you'd be interested in helping out, this would be a huge benefit to me: https://github.com/outr/profig/tree/scala3

**Comment by darkfrog26** [comment]
I don't have the time to get to it until later, but let me know if you have the time to look at it sooner.

**Comment by dwlizlo** [comment]
@darkfrog26 The goal to make tests green, correct? Just making sure as master is currently red :(

**Comment by darkfrog26** [comment]
Travis is failing, but locally the tests should all be working fine for master.

**Comment by dwlizlo** [comment]
I managed to make scala3 branch compile, one test with default attributes is still failing. I will try to figure jt out today.

**Comment by darkfrog26** [comment]
Awesome! Thanks man!

**Comment by darkfrog26** [comment]
You neglected to try testing with Dotty, you are only testing with 2.13.4 I presume?  I'm looking into it now and making some changes.

**Comment by darkfrog26** [comment]
Made a few changes, but I need to figure out what I'm going to do about the Macros for Dotty.

**Comment by dwlizlo** [comment]
I'm down to help, what's the best way to run tests across scala2-scala3?

**Comment by darkfrog26** [comment]
If you update from origin I changed the default to be Scala 3 now, so you'll get lots of fun compilation errors now. :)

**Comment by darkfrog26** [comment]
@dwlizlo please don't think I've forgotten about this. I'm waiting for some dependency libraries to be properly updated and then I'll get to this ASAP.
