### ISSUE TITLE
Make Id[_] covariant

### ISSUE THREAD

**Issue by dwlizlo** [outr/scarango#24]
Currently, Id[Dog] and Id[Cat] cannot be passed as Id[Animal] even if Cat and Dog extend Animal.
Perhaps it wouldn't be so bad an idea to change it? I'm happy to open PR with this one unless there is something I'm missing?

**Comment by darkfrog26** [comment]
I'm okay with that, but shouldn't you be using `Id[Animal]`?

**Comment by dwlizlo** [comment]
I'd like to have some method with shared logic e.g. `def f(id: Id[Animal]) = ???` and pass Id[Cat] or Id[Dog] as parameter
I hope that makes sense?

**Comment by darkfrog26** [comment]
That's fair.

**Comment by darkfrog26** [comment]
Are you still interested in opening a PR for this?

**Comment by dwlizlo** [comment]
Hey, I switched to postgres lately. I will close the issue.
