### ISSUE TITLE
exception during macro expansion: Response processing error

### ISSUE THREAD

**Issue by dpennell** [outr/scarango#25]
I see this in my code.  While investigating, I found the same error in compiling test cases for this repo:

> sbt:scarango> test:compile
[info] compiling 6 Scala sources to /Users/david/gitother/scarango/driver/target/scala-2.13/test-classes ...
[error] /Users/david/gitother/scarango/driver/src/test/scala/spec/AQLSpec.scala:39:19: exception during macro expansion: Response processing error
[error]       val query = aql"FOR user IN users RETURN user"
[error]                   ^
[error] /Users/david/gitother/scarango/driver/src/test/scala/spec/AQLSpec.scala:46:19: exception during macro expansion: Response processing error
[error]       val query = aql"FOR u IN users FILTER u.id == $id && u.name == $name RETURN u"
[error]                   ^
[error] /Users/david/gitother/scarango/driver/src/test/scala/spec/AQLSpec.scala:52:19: exception during macro expansion: Response processing error
[error]       val query = aql"FOR u IN users FILTER u.$field == ${"test"} RETURN u"
... etc

Any idea what could be causing this?

**Comment by darkfrog26** [comment]
The Macro compiler validates the AQL query against a running ArangoDB instance. By default, it expects there to be a running instance at port 8529 with a username and password as `root`. Usually, this type of error tends to happen when it's unable to connect or validate against the database. If you don't have a running instance or don't want to mess with compile-time validations you can use `aqlu` instead.

**Comment by dpennell** [comment]
Thanks!
