### ISSUE TITLE
passing iterator of ArrayBuffer to WritableCollection#batch causes infinte loop

### ISSUE THREAD

**Issue by dpennell** [outr/scarango#26]
In WritableCollection#batch:

` val documents = iterator.take(batchSize).toList`

From the scaladoc for Iterator#take:
> Note:
Reuse: After calling this method, one should discard the iterator it was called on, and use only the iterator that was returned. Using the old iterator is undefined, subject to change, and may result in changes to the new iterator as well.

Workaround - convert ArrayBuffer's to list before passing iterator to WritableCollection#batch

**Comment by darkfrog26** [comment]
Good catch! Feel free to submit a PR if you have the time or I'll try to get to it this week.

**Comment by darkfrog26** [comment]
What version of Scala are you looking at the docs for. I'm not seeing this warning. All I see is the docs for `IterableOnce`:
```
  /** Selects the first ''n'' elements.
    *  $orderDependent
    *  @param  n    the number of elements to take from this $coll.
    *  @return a $coll consisting only of the first `n` elements of this $coll,
    *          or else the whole $coll, if it has less than `n` elements.
    *          If `n` is negative, returns an empty $coll.
    */
```

**Comment by darkfrog26** [comment]
I'm also unable to reproduce any issues using this.

**Comment by dpennell** [comment]
That was in scala 2.12.8.

**Comment by dpennell** [comment]
This code changed between 2.12.x:
https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/Iterator.scala

and 2.13.x:
https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Iterator.scala

I'd just close this ticket.  The workaround is easy enough.
