### ISSUE TITLE
Add Create Database

### ISSUE THREAD

**Issue by ronanM** [outr/scarango#4]
Add the possibility to create a database with the driver ?

https://docs.arangodb.com/3.1/Manual/DataModeling/Databases/WorkingWith.html#create-database

**Comment by darkfrog26** [comment]
I will be tackling this over the next week along with updates for 3.2 support.

**Comment by darkfrog26** [comment]
@ronanM complete database management is now integrated.  I'll be doing a new release as soon as I finish testing with 3.2 and RocksDB.
