### ISSUE TITLE
Add build file instructions for Mill

### ISSUE THREAD

**Issue by nhooey** [outr/scarango#57]
Since you might be modifying the `README.md` anyway, it would be good to add instructions for Mill, a replacement for SBT:

In the `build.sc` file:
```scala
import mill._, scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.13.8"
  def ivyDeps = Agg(
    ivy"com.outr::scarango-driver:3.1.0"
  )
}
```

**Comment by darkfrog26** [comment]
I will add this, but Mill is not a replacement for SBT, it's an alternative. :-p Personally, I don't care for it, but if I don't have to do any work, I'm happy to add this. :)

**Comment by darkfrog26** [comment]
Added

**Comment by nhooey** [comment]
Great!

I’m still just starting out in Scala, and always found SBT such a pain for beginners, with the cryptic error messages and obscure syntax that’s hard to search for problems with.

I’m wondering what you don’t like about Mill and any other problems I might encounter with it as I use it more. It’s been good for me so far, but I’ve barely used it yet.

Can email me at Gmail with the same username if you like.

**Comment by darkfrog26** [comment]
While I agree that SBT could be easier, as complexity grows in the projects you work on, it actually becomes easier while I find Mill gets more complex. Besides, the number of plugins and support for SBT make life much easier whereas Mill often is very hard when you run into a random project that requires an SBT plugin.
