### ISSUE TITLE
CreateDatabase upgrade should be optional

### ISSUE THREAD

**Issue by luisfurnas** [outr/scarango#84]
The `CreateDatabase` upgrade that is run on the `init` makes the following assumptions:
- the database user has read permissions to all databases
- the database doesn't already have the collections, views and store created
- the ArangoDB instance will be single tenant

However I do have a use case that breaks all of those assumptions:
- I have an ArangoDB instance that has one database per tenant
- each tenant has its own user, and those users shouldn't have read permissions to the other tenant's databases
- I need create the collections, views and store before the tenant starts using its database

It would be useful if the `CreateDatabase` upgrade were optional via a boolean passed in the `init` method

**Comment by darkfrog26** [comment]
That's reasonable

**Comment by darkfrog26** [comment]
Merged your PR and it will go out in the next release. Probably sometime this next week. If you need it sooner, let me know.
