### ISSUE TITLE
Is there a tutorial or document for how to use the package?

### ISSUE THREAD

**Issue by git4sun** [outr/scarango#9]
The readme is to brief. Need a document or thorough tutorial to really use it. Like how to set db url, username & password? How to create edges? Is there any document about these? can't learn much from the test.

**Comment by darkfrog26** [comment]
If you'd be interested in helping to support this project, documentation is a very lacking thing right now.

You can learn most of what you might want to do via the tests: https://github.com/outr/scarango/tree/master/driver/src/test/scala/spec

As for URL and credentials, you can supply credentials to the `ArangoSession`and the URL when you instantiate `Arango` or `Graph` depending on how you're using it.

**Comment by git4sun** [comment]
How can I close a db session in the managed scenario? I saw the `ArangoSession` has a `instance` with a `dispose()` method. Is that the way to close connection when finish? If yes, how can I get the session from the managed object extends Graph?

**Comment by darkfrog26** [comment]
Looks like this hasn't been exposed properly.  You are welcome to submit a PR to create a `dispose` method on `Graph` that calls the session's dispose method.  However, it should be unnecessary as all communication with ArangoDB is done via RESTful calls, so active connections are retained, it's just purely some cleanup.

**Comment by git4sun** [comment]
What do you mean by "active connections are retained"? I need a close or dispose function to signal the termination of program. what if I have multiple processes in other projects with other language, which depends on the finish of the scala process? If I don't close, then I have to write the status to a database or something to notify other programs that this process is done.

**Comment by git4sun** [comment]
btw, I got `remote: Permission to outr/scarango.git denied` error when trying to push a new branch.

**Comment by darkfrog26** [comment]
You don't have to dispose, just let the application terminate or do `sys.exit(0)` if you want to force it. Unless I misunderstand what you mean, no disposing is necessary as no connections remain active when not actually calling the database.

Regarding new branches, the standard process on GitHub is to fork the repo, push your changes to your fork, then create a pull request back.

**Comment by git4sun** [comment]
I see. I don't need close then. Thanks.
