### ISSUE TITLE
Dependency on Scribe brings an SLF4J binding to the classpath, which conflicts with  other backends

### ISSUE THREAD

**Issue by oridag** [outr/scarango#94]
Libraries should not depend on an SLF4J binding (dependency on slf4j-api is ok). Bringing in that binding to the classpath imposes a backend on the application.

**Comment by darkfrog26** [comment]
I'll investigate this, but I believe the Java ArangoDB driver that this builds on is using SLF4J, so I incorporated scribe-slf4j to better manage it.

**Comment by oridag** [comment]
Libraries should always write logs to a facade (the de-facto standard is SLF4J), never to a backend. It's the application that plugs in the backend that does the actual writing of the logs to a destination.

**Comment by darkfrog26** [comment]
I can't say I 100% agree, but it doesn't harm anything to change it, so I removed it. :)

Do you have any need to have a new release sooner than later?
